name: Build & Push Docker Image (Docker Hub)

on:
  push:
    branches: ['main', 'build-and-push']
    tags:
      - 'v1.1.0'

permissions:
  contents: read

env:
  IMAGE_NAME: mizzcode/portofolio

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE_NAME }}
          tags: |
            # Mengambil versi dari Git Tag, misal: v1.2.3 -> 1.2.3
            type=semver,pattern={{version}}
            # Menambah tag 'latest' jika build terjadi di branch main
            type=raw,value=latest,enable={{is_default_branch}}
            # Tetap membuat tag berdasarkan commit SHA untuk referensi
            type=sha,prefix=

      - name: Build and push
        id: build-and-push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=registry,ref=${{ env.IMAGE_NAME }}:buildcache
          cache-to: type=registry,ref=${{ env.IMAGE_NAME }}:buildcache,mode=max

      - name: Print Image Digest
        run: echo ${{ steps.build-and-push.outputs.digest }}
